services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  mint:
    env_file:
      - path: ".env"
        required: true
    environment:
      DOCKER: "true"
    build: ./
    ports:
      - 8080:8080
    restart: on-failure:10
    depends_on:
      - db
    volumes:
      - /var/log/nutmix:/var/log/nutmix
      - ${HOME}/.config/nutmix:/root/.config/nutmix
volumes:
  db:
    driver: local
