name: Publish Docker image on tag

on:
  push:
    tags: ['v*'] 

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nutmix:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nutmix:latest

      - name: Image details
        run: |
          echo "Pushed image: ${{ secrets.DOCKERHUB_USERNAME }}/nutmix:${{ github.ref_name }}"
