name: Release on Tag Push

on:
  push:
    tags:
      - "v*" # Trigger on any tag push

permissions:
  contents: write # Needed to create releases and upload artifacts

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      # Step 3: Install Just
      - name: Install Just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      # Step 4: Run the release task
      - name: Run release task
        run: just release

      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ endsWith(github.ref_name, '-prelease') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            release/*
          allowUpdates: true
