name: Release on Tag Push

on:
  push:
    tags:
      - 'v*'     # Trigger on any tag push

permissions:
  contents: write # Needed to create releases and upload artifacts

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Run templ build
        run: templ generate .

      - name: Build Linux binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o nutmix ./cmd/nutmix/main.go

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ endsWith(github.ref_name, '-prelease') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            ./nutmix
